name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  cpu_windows_build:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: enable dev cmd prompt
        uses: ./
      - name: build
        shell: cmd
        run: make OS=WINDOWS COMPILER=cl COMPILER_TYPE=MSVC
    
  cpu_linux_build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: dependencies
        run: | 
          sudo apt-get update 
          sudo apt-get install -y \
            uuid-dev \
            build-essential
      - name: build
        run: make OS=LINUX compiler=g++ COMPILER_TYPE=GNU

  cpu_macos_build:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: build
        run: make OS=MACOS compiler=clang COMPILER_TYPE=CLANG
