name: MacOS

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  cpu_macos_x86_build:
    name: MacOS_x86
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build QuESTlink
        run: make OS=MACOS compiler=clang COMPILER_TYPE=CLANG MACOS_ARCH=x64
  cpu_macos_arm_build:
    name: MacOS_ARM
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build QuESTlink
        run: make OS=MACOS compiler=clang COMPILER_TYPE=CLANG MACOS_ARCH=ARM